### ISSUE TITLE
CSS static file not installed in right folder

### ISSUE THREAD

**Issue by VenturaFranklin** [Salaah01/django-email-signals#14]
On a clean install of v1.0.7 the CSS static file is at: 
`email_signals\static\css\signal_change_form.min.css` 
instead of 
`email_signals\static\email_signals\css\signal_change_form.min.css`

This messes up the admin display of the signals models. https://github.com/Salaah01/django-email-signals/blob/013a54845ece18eed4eed61e6d2eabae53cbc959/email_signals/admin.py#L26

**Comment by Salaah01** [comment]
Good catch!
It looks like I must've somehow managed to move the file at some point.
I'll do a few other bits and the create a new release.

Thank you!

**Comment by Salaah01** [comment]
All fixed and released in [version 1.0.8](https://pypi.org/project/django-email-signals/1.0.8/).
Thank you again for raising this!
