### ISSUE TITLE
Admin Configurable Send To 

### ISSUE THREAD

**Issue by VenturaFranklin** [Salaah01/django-email-signals#7]
I would like to be able to allow the admin to configure a list of emails to send to instead of needing to predefine mailing lists in model methods. I see that there was a "to_emails_opt" that was removed and so wanted to discuss with you before a Pull Request. 
I propose:
- Alter mailing_list to TextField for a greater length
    - help text will be "The mailing list to send the signal to. Either enter a comma separated list of emails or the app will search for a function with the same name in the model instance."
- Adjust email_signal_recipients to check if method and if not check for @ and if @ split on "," and make that the email list 
- Update validation and docs

What do you think?

Overall great project! I would definitely extend the `EmailSignalMixin` with some default often used methods with emails, but sometimes the users want to send a signal to someone I didn't think of and adding option to just set the email would be great!

**Comment by Salaah01** [comment]
Hi Ventura,
Thank you very much for your kind words!
I agree that having the ability to add email addresses directly could be useful.
I didn't quite understand your suggestion relating to the `EmailSignalMixin` would you be able to elaborate please?

**Comment by VenturaFranklin** [comment]
I finally had a chance to make a PR. Please let me know what you think.

> I didn't quite understand your suggestion relating to the EmailSignalMixin would you be able to elaborate please?
I was saying that I could just make my own classes like so

```python
from email_signals.models import EmailSignalMixin

class EmailSignalMixinDefault(EmailSignalMixin):
    def my_mailing_list_that_everyone_uses():
        return ["email1", "email2"]
```
And then just use `EmailSignalMixinDefault` everywhere. No changes needed, just saying that this solves only part of the problem, but my PR allowing any admin to set any email really solves the issue.

**Comment by Salaah01** [comment]
Ah I see, this is actually a good idea. It's almost like a mixin for the mixin.
Also, PR approved and merged! Thank for contributing!
