### ISSUE TITLE
Django 3.0+ Required

### ISSUE THREAD

**Issue by VenturaFranklin** [Salaah01/django-email-signals#8]
https://github.com/Salaah01/django-email-signals/blob/f05a80e5fa1ae26e58e69eee567417b6d483403e/setup.cfg#L30

In the config Django 2.2+ is listed as required but [Singal.SignalTypeChoices](https://github.com/Salaah01/django-email-signals/blob/a968e38ab346c852850e38cc92b19250e9204ef9/email_signals/models.py#L34) uses `models.TextChoices` which was introduced in Django 3.0.

**Comment by Salaah01** [comment]
Good catch!
I'll update that

**Comment by Salaah01** [comment]
Good catch!
I'll change that later tonight and just double-check all the other packages.
